# Generated by Django 5.2.1 on 2025-05-08 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('news', 'News'), ('announcement', 'Announcement'), ('urgent', 'Urgent'), ('research', 'Research')], max_length=20)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('tags', models.CharField(help_text='Comma-separated tags', max_length=255)),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_branches', models.JSONField(blank=True, null=True)),
                ('target_years', models.JSONField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
